### ISSUE TITLE
-p PNG not working properly

### ISSUE THREAD

**Issue by kaltu** [MRSRL/mridata-recon#1]
imageio error:
`ValueError: Could not find a format to write the specified file in mode 'i'`

In Windows:
```
FSE phase correction...
Transforming k-space data to image domain...
Writing files...
Writing example png...
Traceback (most recent call last):
  File "D:\projects\mridata-recon-master\recon_2d_fse.py", line 265, in <module>
    file_png=args.png, verbose=args.verbose)
  File "D:\projects\mridata-recon-master\recon_2d_fse.py", line 247, in dataset_to_cfl
    imageio.imwrite(file_png, image_out.astype(np.uint8))
  File "C:\Program Files\Python35\lib\site-packages\imageio\core\functions.py", line 244, in imwrite
    writer = get_writer(uri, format, 'i', **kwargs)
  File "C:\Program Files\Python35\lib\site-packages\imageio\core\functions.py", line 170, in get_writer
    'in mode %r' % mode)
ValueError: Could not find a format to write the specified file in mode 'i'
```
In Linux:
```
Transforming k-space data to image domain...
Writing files...
Writing example png...
Traceback (most recent call last):
File "/Data2/sruser/projects/mridata-recon-master/recon_2d_fse.py", line 265, in <module>
file_png=args.png, verbose=args.verbose)
File "/Data2/sruser/projects/mridata-recon-master/recon_2d_fse.py", line 247, in dataset_to_cfl
imageio.imwrite(file_png, image_out.astype(np.uint8))
File "/Data2/sruser/PycharmProjects/superres/venv/lib/python3.5/site-packages/imageio/core/functions.py", line 244, in imwrite
writer = get_writer(uri, format, 'i', **kwargs)
File "/Data2/sruser/PycharmProjects/superres/venv/lib/python3.5/site-packages/imageio/core/functions.py", line 170, in get_writer
'in mode %r' % mode)
ValueError: Could not find a format to write the specified file in mode 'i'
```

any ideas?

**Comment by jychengmri** [comment]
What did you give as an argument for `-p`? It should be the name of the file that you want to write, so `-p image.png`. Try that --- hopefully that works! I should make it clearer in the code.
